### ISSUE TITLE
When using @MyBatisResourcesScan [mvn install], com.sun.tools.javac.code.Symbol$CompletionFailure: the [org.springframework.nativex.hint.TypeAccess] class file cannot be found

### ISSUE THREAD

**Issue by admintertar** [mybatis/spring-native#117]
When using @MyBatisResourcesScan [mvn install], com.sun.tools.javac.code.Symbol$CompletionFailure: the [org.springframework.nativex.hint.TypeAccess] class file cannot be found

[INFO] --- maven-compiler-plugin:3.11.0:compile (default-compile) @ mnative ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 6 source files with javac [debug release 17] to target\classes
编译器 (17.0.5) 中出现异常错误。如果在 Bug Database (http://bugs.java.com) 中没有找到该错误，请通过 Java Bug 报告页 (http://bugreport.java.com) 建立该 Java 编译器 Bug。请在报告中附上您的程序、以下诊断信息以及传递到 Java 编译器的参数。谢谢。
com.sun.tools.javac.code.Symbol$CompletionFailure: 找不到org.springframework.nativex.hint.TypeAccess的类文件

Success can be achieved without using @ MyBatisResourcesScan [mvn install]

springboot-version:3.1.5
mybatis-spring-boot-starter:3.0.2
mybatis-spring-native-core:0.1.0-SNAPSHOT

java version "17.0.5" 2022-10-18 LTS
Java(TM) SE Runtime Environment GraalVM EE 22.3.0 (build 17.0.5+9-LTS-jvmci-22.3-b07)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 22.3.0 (build 17.0.5+9-LTS-jvmci-22.3-b07, mixed mode, sharing)

**Comment by admintertar** [comment]
https://github.com/admintertar/mnative/tree/master

**Comment by admintertar** [comment]
https://github.com/kazuki43zoo/mybatis-native-demo/tree/spring-boot-3.1

**Comment by 18028798638** [comment]
你好，请问你是怎么解决的？

**Comment by admintertar** [comment]
> 你好，请问你是怎么解决的？

https://github.com/kazuki43zoo/mybatis-native-demo/blob/spring-boot-3.1/src/main/java/com/example/nativedemo/MyBatisNativeConfiguration.java

**Comment by 18028798638** [comment]
> > 你好，请问你是怎么解决的？
> 
> https://github.com/kazuki43zoo/mybatis-native-demo/blob/spring-boot-3.1/src/main/java/com/example/nativedemo/MyBatisNativeConfiguration.java

我在项目中添加了这个配置类，但还是报一样的错

**Comment by admintertar** [comment]
> > > 你好，请问你是怎么解决的？
> > 
> > 
> > https://github.com/kazuki43zoo/mybatis-native-demo/blob/spring-boot-3.1/src/main/java/com/example/nativedemo/MyBatisNativeConfiguration.java
> 
> 我在项目中添加了这个配置类，但还是报一样的错

不要加MyBatisResourcesScan注解试试

**Comment by 18028798638** [comment]
> > > > 你好，请问你是怎么解决的？
> > > 
> > > 
> > > https://github.com/kazuki43zoo/mybatis-native-demo/blob/spring-boot-3.1/src/main/java/com/example/nativedemo/MyBatisNativeConfiguration.java
> > 
> > 
> > 我在项目中添加了这个配置类，但还是报一样的错
> 
> 不要加MyBatisResourcesScan注解试试

不加这个注解的话，本地能正常运行，但是native-image生成的exe文件读取不到mapper.xml文件😂

**Comment by admintertar** [comment]
> > > > > 你好，请问你是怎么解决的？
> > > > 
> > > > 
> > > > https://github.com/kazuki43zoo/mybatis-native-demo/blob/spring-boot-3.1/src/main/java/com/example/nativedemo/MyBatisNativeConfiguration.java
> > > 
> > > 
> > > 我在项目中添加了这个配置类，但还是报一样的错
> > 
> > 
> > 不要加MyBatisResourcesScan注解试试
> 
> 不加这个注解的话，本地能正常运行，但是native-image生成的exe文件读取不到mapper.xml文件😂

看一下这里的配置，hints.resources()
                      .registerPattern(mapperInterfaceType.getName().replace('.', '/').concat(".xml"))  根据类路径去resource下面找.xml的文件，看看你的resouce下面是不是按照这个包名的
