### ISSUE TITLE
@MyBatisResourcesScan occurred error on windows about mapperLocationPatterns

### ISSUE THREAD

**Issue by iygnol** [mybatis/spring-native#22]
My code is like this below:
@MyBatisResourcesScan(mapperLocationPatterns = "classpath*:**/mapper/*Mapper.xml")
The error log :(Removed private information)
java.io.UncheckedIOException: org.springframework.core.NestedIOException: Invalid URI [jar:file:G:\.m2\repository\net\xxxxx\user-base\1.0.0\user-base-1.0.0.jar!/base/mapper/SysUserMapper.xml]; nested exception is java.net.URISyntaxException: Illegal character in opaque part at index xx: jar:file:G:\.m2\repository\net\xxxxx\user-base\1.0.0\user-base-1.0.0.jar!/base/mapper/SysUserMapper.xml

This error should be caused by windows backslashes, I don't know how to fix it.

**Comment by awxiaoxian2020** [comment]
Could you give a demo?

**Comment by kazuki43zoo** [comment]
@iygnol Cloud your provide a small reproduce project via GitHub?

**Comment by iygnol** [comment]
I wrote a demo, the link is below


https://github.com/iygnol/mybatis-springnative-demo




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mybatis/spring-native"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月5日(星期天) 上午10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mybatis/spring-native] @MyBatisResourcesScan occurred error on windows about mapperLocationPatterns (Issue #22)





 
@iygnol Cloud your provide a small reproduce project via GitHub?

**Comment by iygnol** [comment]
I wrote a demo, the link is below


https://github.com/iygnol/mybatis-springnative-demo



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mybatis/spring-native"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月14日(星期六) 下午5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mybatis/spring-native] @MyBatisResourcesScan occurred error on windows about mapperLocationPatterns (Issue #22)





 
Could you give a demo?

**Comment by kazuki43zoo** [comment]
@iygnol Thx for providing reproduce project!! I can reproduce this issue my local environment.

**Comment by kazuki43zoo** [comment]
@iygnol I've fixed this issue and published SNAPSHOT version on Sonatype OSS repository.

**Comment by iygnol** [comment]
Thank you!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mybatis/spring-native"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月6日(星期一) 凌晨0:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mybatis/spring-native] @MyBatisResourcesScan occurred error on windows about mapperLocationPatterns (Issue #22)





 
@iygnol I've fixed this issue and published SNAPSHOT version on Sonatype OSS repository.
