### ISSUE TITLE
Add workflow for SonarCloud 

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-native#5]

**Comment by kazuki43zoo** [comment]
@harawata Could you set environment variable for accessing SonarQube?

**Comment by harawata** [comment]
HI @kazuki43zoo ,
I generated a new sonar token and added it as a repository secret.
If there is anything else I should do, please let me know.

**Comment by kazuki43zoo** [comment]
@harawata Thanks!! I will try to add workflow!!

**Comment by kazuki43zoo** [comment]
@hazendaz The sonar:sonar  failed. Do you know the cause?

* https://github.com/mybatis/spring-native/blob/master/.github/workflows/sonar.yaml
* https://github.com/mybatis/spring-native/actions/runs/1773151013

**Comment by hazendaz** [comment]
@kazuki43zoo I think it needed setup in sonar as well.  I have set it up there and its running currently.  It did provide a new key for sonar so I just used what it showed and updated it here.  I don't think that matters too much as we can change at any time.  Will continue to watch and see if that does it.

**Comment by hazendaz** [comment]
That resolved it.  So for reference, to create new one go into sonar and look up mybatis projects.  New ones will not be checked, simply check them to create the entry, get the token to use, it can be changed to use any there, then pretty much good to go.

See https://sonarcloud.io/project/overview?id=mybatis_spring-native
