### ISSUE TITLE
Add workflow for Coveralls

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-native#6]

**Comment by kazuki43zoo** [comment]
@harawata Could you set environment variable for accessing Coveralls?

**Comment by harawata** [comment]
Hi @kazuki43zoo ,

You just need to copy `.github/workflows/coveralls.yaml` from another repo, it seems.

**Comment by kazuki43zoo** [comment]
@harawata Thanks for reaction!! I will try to add workflow!!
