### ISSUE TITLE
Spring Boot  version :3.0.0-RC1  ;mybatis-spring-boot-starter version :3.0.0-SNAPSHOT  When can it be supported?

### ISSUE THREAD

**Issue by csx-bill** [mybatis/spring-native#65]
Spring Boot  version :3.0.0-RC1  ;mybatis-spring-boot-starter version :3.0.0-SNAPSHOT  When can it be supported?

**Comment by linghengqian** [comment]
- Can you provide a minimal reproducible example for tracking this issue?  This repository is blocked by https://github.com/mybatis/spring-native/issues/39 and Oracle tracks JEP-290 issues in its internal system.

**Comment by kazuki43zoo** [comment]
We have plan to support Spring Boot 3.x, But now does not support Spring Boot 3.x yet.

See https://github.com/mybatis/spring-native/issues/36
